[versions]
agp = "8.10.1"
kotlin = "2.1.21"
compose-compiler = "1.5.11"
coroutine = "1.10.1"
composeBom = "2025.06.00"
activityCompose = "1.10.1"
lifecycleRuntimeKtx = "2.9.1"
navigation = "1.0.0-beta01"
navigation-lifecycle = "1.0.0-alpha04"
room = "2.7.1"
coreKtx = "1.16.0"
hilt = "2.56.2"
hilt-navigation = "1.2.0"
retrofit = "2.11.0"
uiToolingPreview = "1.9.4"
uiTooling = "1.9.4"
material3 = "1.4.0"


[libraries]
#COMPOSE
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
foundation = { module = "androidx.compose.foundation:foundation" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }


#NAVIGATION
navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation" }
navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation" }
lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "navigation-lifecycle" }

#ROOM
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

#CORE KTX
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }

#HILT
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation" }

#RETROFIT
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

#COROUTINES
coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiToolingPreview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }


[plugins]
#ANDROID GRADLE PLUGINS
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library" }

#KOTLIN PLUGINS
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

#HILT PLUGINS
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

#KAPT
kapt = { id = "org.jetbrains.kotlin.kapt" }